model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQCirModel
  monitor: val/rec_loss_epoch
  params:
    # ckpt_path: 
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.2
        codebook_weight: 1.0

data:
  target: taming.data.utils.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrainHolistic
      params:
        training_images_list_file: ./train.txt
        size: 256
        holistic: 128
    validation:
      target: taming.data.custom.CustomTestHolistic
      params:
        test_images_list_file: ./test.txt
        size: 256
        holistic: 128


lightning:
  callbacks:
    image_logger:
      target: taming.data.utils.ImageLogger
      params:
        batch_frequency: 10000
        max_images: 2
        increase_log_steps: False
