model:
  base_learning_rate: 4.5e-06
  target: taming.models.global_sampler.GlobalSamplerWithCLIP
  params:
    cond_stage_key: knn
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 133
        n_layer: 12
        n_head: 8
        n_embd: 1024
    first_stage_config:
      target: taming.models.vqgan.VQCirModel
      params:
        ckpt_path: 
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.modules.misc.coord.CoordStage
      params:
        n_embed: 1024
        down_factor: 16
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrainHolistic
      params:
        training_images_list_file: /mnt/disk10T/sxc/360_gen/comparisons/taming-transformers/mp360-512x1024/fix/train.txt
        size: 256
        holistic: 128
        clip_emb: clip_emb.npy
    validation:
      target: taming.data.custom.CustomTestHolistic
      params:
        test_images_list_file: /mnt/disk10T/sxc/360_gen/comparisons/taming-transformers/mp360-512x1024/fix/test.txt
        size: 256
        holistic: 128
        clip_emb: clip_emb.npy
